const jobs = [
    {
        title: "Information Technology",
        company: "ABC1 Tech",
        location: "New York, NY",
        posted: "2 days ago",
        salary: "$80,000 - $100,000",
        image: "assets/logos/logo_1.1.png",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
        companyDescription: "ABC Tech is a leading tech company specializing in software development and IT consulting. We offer a dynamic and inclusive work environment.",
        icon: "it.png",
        term: "3 year+",
        position: "manager",
        experience: "4 - 6 year",
        category: "Information Technology",
    },
    {
        "title": "Software Engineer",
        "company": "ABC Tech",
        "location": "New York, NY",
        "posted": "2 days ago",
        "salary": "$80,000 - $100,000",
        "image": "assets/logos/logo_1.1.png",
        "description": "Develop and maintain software applications. Collaborate with cross-functional teams.",
        "companyDescription": "ABC Tech is a leading tech company specializing in software development and IT consulting. We offer a dynamic and inclusive work environment.",
        "icon": "it.png",
        "term": "3 year+",
        "position": "Manager",
        "experience": "4 - 6 years",
        "category": "Information Technology"
    },
    {
        "title": "Network Administrator",
        "company": "Net Solutions",
        "location": "San Jose, CA",
        "posted": "1 week ago",
        "salary": "$70,000 - $85,000",
        "image": "assets/logos/logo_1.2.png",
        "description": "Manage and maintain network infrastructure. Ensure network security and performance.",
        "companyDescription": "Net Solutions is a leading provider of network services and solutions.",
        "icon": "it.png",
        "term": "3 year+",
        "position": "Administrator",
        "experience": "3 - 5 years",
        "category": "Information Technology"
    },
    {
        "title": "Systems Analyst",
        "company": "Data Corp",
        "location": "Dallas, TX",
        "posted": "5 days ago",
        "salary": "$75,000 - $95,000",
        "image": "assets/logos/logo_1.3.png",
        "description": "Analyze and improve IT systems and processes. Work with stakeholders to gather requirements.",
        "companyDescription": "Data Corp specializes in providing data-driven solutions for various industries.",
        "icon": "it.png",
        "term": "3 year+",
        "position": "Analyst",
        "experience": "4 - 6 years",
        "category": "Information Technology"
    },
    {
        "title": "IT Support Specialist",
        "company": "Tech Help",
        "location": "Miami, FL",
        "posted": "3 days ago",
        "salary": "$50,000 - $65,000",
        "image": "assets/logos/logo_1.4.png",
        "description": "Provide technical support to end-users. Troubleshoot hardware and software issues.",
        "companyDescription": "Tech Help offers comprehensive IT support services to businesses and individuals.",
        "icon": "it.png",
        "term": "2 year+",
        "position": "Specialist",
        "experience": "2 - 4 years",
        "category": "Information Technology"
    },
    {
        "title": "Database Administrator",
        "company": "Data Solutions",
        "location": "Chicago, IL",
        "posted": "1 week ago",
        "salary": "$85,000 - $105,000",
        "image": "assets/logos/logo_1.5.png",
        "description": "Manage and maintain databases. Ensure data integrity and security.",
        "companyDescription": "Data Solutions is a leader in providing data management services to enterprises.",
        "icon": "it.png",
        "term": "4 year+",
        "position": "Administrator",
        "experience": "5 - 7 years",
        "category": "Information Technology"
    },
    {
        "title": "Cloud Engineer",
        "company": "CloudTech",
        "location": "Seattle, WA",
        "posted": "4 days ago",
        "salary": "$90,000 - $110,000",
        "image": "assets/logos/logo_1.6.png",
        "description": "Design and implement cloud solutions. Manage cloud infrastructure.",
        "companyDescription": "CloudTech specializes in cloud computing solutions and services.",
        "icon": "it.png",
        "term": "3 year+",
        "position": "Engineer",
        "experience": "4 - 6 years",
        "category": "Information Technology"
    },{
          "title": "DevOps Engineer",
          "company": "DevWorks",
          "location": "Austin, TX",
          "posted": "2 days ago",
          "salary": "$85,000 - $105,000",
          "image": "assets/logos/logo_1.7.png",
          "description": "Automate and streamline software development and deployment processes.",
          "companyDescription": "DevWorks provides innovative DevOps solutions to enhance software development efficiency.",
          "icon": "it.png",
          "term": "3 year+",
          "position": "Engineer",
          "experience": "4 - 6 years",
          "category": "Information Technology"
      },
      {
          "title": "Cybersecurity Analyst",
          "company": "SecureIT",
          "location": "Boston, MA",
          "posted": "1 week ago",
          "salary": "$80,000 - $100,000",
          "image": "assets/logos/logo_1.8.png",
          "description": "Identify and mitigate cybersecurity threats. Implement security measures.",
          "companyDescription": "SecureIT specializes in providing advanced cybersecurity solutions to protect businesses.",
          "icon": "it.png",
          "term": "4 year+",
          "position": "Analyst",
          "experience": "4 - 6 years",
          "category": "Information Technology"
      },
      {
          "title": "IT Project Manager",
          "company": "Project Solutions",
          "location": "Denver, CO",
          "posted": "3 days ago",
          "salary": "$90,000 - $110,000",
          "image": "assets/logos/logo_1.9.png",
          "description": "Manage and oversee IT projects. Ensure timely and successful project completion.",
          "companyDescription": "Project Solutions specializes in IT project management and consulting services.",
          "icon": "it.png",
          "term": "5 year+",
          "position": "Manager",
          "experience": "5 - 7 years",
          "category": "Information Technology"
      },
      {
          "title": "Business Analyst",
          "company": "BizTech",
          "location": "Atlanta, GA",
          "posted": "4 days ago",
          "salary": "$75,000 - $95,000",
          "image": "assets/logos/logo_1.10.png",
          "description": "Analyze business processes and requirements. Provide recommendations for improvements.",
          "companyDescription": "BizTech offers business consulting and technology solutions to enhance operational efficiency.",
          "icon": "it.png",
          "term": "3 year+",
          "position": "Analyst",
          "experience": "4 - 6 years",
          "category": "Information Technology"
      },
      {
          "title": "Office Administrator",
          "company": "XYZ Corp",
          "location": "San Francisco, CA",
          "posted": "5 days ago",
          "salary": "$50,000 - $60,000",
          "image": "assets/logos/logo_2.1.png",
          "description": "Manage office operations and support staff. Ensure efficient office procedures.",
          "companyDescription": "XYZ Corp is a multinational company providing innovative solutions in various industries.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Coordinator",
          "experience": "3 - 5 years",
          "category": "Administrator"
      },
      {
          "title": "Administrative Assistant",
          "company": "Office Pro",
          "location": "New York, NY",
          "posted": "3 days ago",
          "salary": "$40,000 - $50,000",
          "image": "assets/logos/logo_2.2.png",
          "description": "Provide administrative support to the team. Manage schedules and correspondence.",
          "companyDescription": "Office Pro offers administrative support services to various businesses.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Assistant",
          "experience": "2 - 3 years",
          "category": "Administrator"
      },
      {
          "title": "Executive Assistant",
          "company": "Global Enterprises",
          "location": "Chicago, IL",
          "posted": "1 week ago",
          "salary": "$55,000 - $70,000",
          "image": "assets/logos/logo_2.3.png",
          "description": "Support senior executives. Manage calendars, travel arrangements, and communication.",
          "companyDescription": "Global Enterprises is a leading multinational company with diverse business interests.",
          "icon": "admin.png",
          "term": "3 year+",
          "position": "Assistant",
          "experience": "4 - 6 years",
          "category": "Administrator"
      },
      {
          "title": "Receptionist",
          "company": "Front Desk Inc.",
          "location": "Los Angeles, CA",
          "posted": "2 days ago",
          "salary": "$30,000 - $40,000",
          "image": "assets/logos/logo_2.4.png",
          "description": "Greet visitors and manage front desk operations. Handle phone calls and inquiries.",
          "companyDescription": "Front Desk Inc. provides front office solutions and services to businesses.",
          "icon": "admin.png",
          "term": "1 year+",
          "position": "Receptionist",
          "experience": "1 - 2 years",
          "category": "Administrator"
      },
      {
          "title": "HR Administrator",
          "company": "PeopleFirst",
          "location": "Houston, TX",
          "posted": "4 days ago",
          "salary": "$45,000 - $60,000",
          "image": "assets/logos/logo_2.5.png",
          "description": "Manage HR operations and employee records. Support recruitment and onboarding processes.",
          "companyDescription": "PeopleFirst specializes in human resources and talent management services.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Administrator",
          "experience": "3 - 5 years",
          "category": "Administrator"
      },
      {
          "title": "Office Manager",
          "company": "BizOffice",
          "location": "Seattle, WA",
          "posted": "3 days ago",
          "salary": "$60,000 - $75,000",
          "image": "assets/logos/logo_2.6.png",
          "description": "Oversee office operations and staff. Ensure efficient workflow and productivity.",
          "companyDescription": "BizOffice provides office management solutions to enhance business efficiency.",
          "icon": "admin.png",
          "term": "3 year+",
          "position": "Manager",
          "experience": "4 - 6 years",
          "category": "Administrator"
      },
      {
          "title": "Data Entry Clerk",
          "company": "DataWorks",
          "location": "Boston, MA",
          "posted": "1 week ago",
          "salary": "$35,000 - $45,000",
          "image": "assets/logos/logo_2.7.png",
          "description": "Enter and update data in systems. Ensure accuracy and data integrity.",
          "companyDescription": "DataWorks offers data entry and management services to businesses.",
          "icon": "admin.png",
          "term": "1 year+",
          "position": "Clerk",
          "experience": "1 - 2 years",
          "category": "Administrator"
      },
      {
          "title": "Logistics Coordinator",
          "company": "LogiTech",
          "location": "Miami, FL",
          "posted": "5 days ago",
          "salary": "$50,000 - $65,000",
          "image": "assets/logos/logo_2.8.png",
          "description": "Coordinate logistics and supply chain operations. Manage shipments and inventory.",
          "companyDescription": "LogiTech specializes in logistics and supply chain management solutions.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Coordinator",
          "experience": "3 - 5 years",
          "category": "Administrator"
      },
      {
          "title": "Customer Service Administrator",
          "company": "ClientFirst",
          "location": "Atlanta, GA",
          "posted": "4 days ago",
          "salary": "$45,000 - $55,000",
          "image": "assets/logos/logo_2.9.png",
          "description": "Manage customer service operations. Handle customer inquiries and support requests.",
          "companyDescription": "ClientFirst provides customer service and support solutions to businesses.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Administrator",
          "experience": "2 - 4 years",
          "category": "Administrator"
      },
      {
          "title": "Project Administrator",
          "company": "ProjManage",
          "location": "Denver, CO",
          "posted": "3 days ago",
          "salary": "$55,000 - $70,000",
          "image": "assets/logos/logo_2.10.png",
          "description": "Support project managers in planning and executing projects. Maintain project documentation.",
          "companyDescription": "ProjManage offers project management and administrative support services.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Administrator",
          "experience": "3 - 5 years",
          "category": "Administrator"
      },
      {
          "title": "Architect",
          "company": "Design Innovations",
          "location": "Chicago, IL",
          "posted": "3 days ago",
          "salary": "$70,000 - $90,000",
          "image": "assets/logos/logo_3.1.png",
          "description": "Design and oversee construction projects. Work with clients to meet their needs.",
          "companyDescription": "Design Innovations is a top architecture firm known for innovative and sustainable designs.",
          "icon": "architecture.png",
          "term": "5 year+",
          "position": "Senior Architect",
          "experience": "7 - 10 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Civil Engineer",
          "company": "BuildRight",
          "location": "New York, NY",
          "posted": "4 days ago",
          "salary": "$80,000 - $100,000",
          "image": "assets/logos/logo_3.2.png",
          "description": "Plan and oversee construction projects. Ensure compliance with regulations.",
          "companyDescription": "BuildRight specializes in civil engineering and construction management services.",
          "icon": "architecture.png",
          "term": "5 year+",
          "position": "Engineer",
          "experience": "5 - 7 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Mechanical Engineer",
          "company": "TechMech",
          "location": "Los Angeles, CA",
          "posted": "5 days ago",
          "salary": "$75,000 - $95,000",
          "image": "assets/logos/logo_3.3.png",
          "description": "Design and develop mechanical systems. Conduct performance testing and analysis.",
          "companyDescription": "TechMech offers innovative mechanical engineering solutions for various industries.",
          "icon": "architecture.png",
          "term": "3 year+",
          "position": "Engineer",
          "experience": "4 - 6 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Electrical Engineer",
          "company": "ElectroTech",
          "location": "San Francisco, CA",
          "posted": "1 week ago",
          "salary": "$80,000 - $100,000",
          "image": "assets/logos/logo_3.4.png",
          "description": "Design and implement electrical systems. Ensure safety and efficiency.",
          "companyDescription": "ElectroTech specializes in electrical engineering and power systems.",
          "icon": "architecture.png",
          "term": "4 year+",
          "position": "Engineer",
          "experience": "5 - 7 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Structural Engineer",
          "company": "Structura",
          "location": "Seattle, WA",
          "posted": "3 days ago",
          "salary": "$85,000 - $105,000",
          "image": "assets/logos/logo_3.5.png",
          "description": "Design and analyze structural components. Ensure structural integrity and safety.",
          "companyDescription": "Structura offers structural engineering services for residential and commercial projects.",
          "icon": "architecture.png",
          "term": "4 year+",
          "position": "Engineer",
          "experience": "5 - 7 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Urban Planner",
          "company": "CityPlan",
          "location": "Boston, MA",
          "posted": "2 days ago",
          "salary": "$70,000 - $90,000",
          "image": "assets/logos/logo_3.6.png",
          "description": "Develop and implement urban planning projects. Work with city officials and stakeholders.",
          "companyDescription": "CityPlan specializes in urban planning and sustainable development projects.",
          "icon": "architecture.png",
          "term": "3 year+",
          "position": "Planner",
          "experience": "4 - 6 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Landscape Architect",
          "company": "GreenScapes",
          "location": "Denver, CO",
          "posted": "1 week ago",
          "salary": "$65,000 - $85,000",
          "image": "assets/logos/logo_3.7.png",
          "description": "Design and plan outdoor spaces. Ensure sustainable and aesthetic landscape solutions.",
          "companyDescription": "GreenScapes offers landscape architecture services for residential and commercial properties.",
          "icon": "architecture.png",
          "term": "3 year+",
          "position": "Architect",
          "experience": "4 - 6 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Industrial Engineer",
          "company": "IndusTech",
          "location": "Houston, TX",
          "posted": "4 days ago",
          "salary": "$75,000 - $95,000",
          "image": "assets/logos/logo_3.8.png",
          "description": "Optimize manufacturing processes. Improve efficiency and reduce costs.",
          "companyDescription": "IndusTech specializes in industrial engineering and process optimization services.",
          "icon": "architecture.png",
          "term": "4 year+",
          "position": "Engineer",
          "experience": "5 - 7 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Environmental Engineer",
          "company": "EcoTech",
          "location": "Miami, FL",
          "posted": "5 days ago",
          "salary": "$70,000 - $90,000",
          "image": "assets/logos/logo_3.9.png",
          "description": "Develop and implement environmental protection plans. Conduct impact assessments.",
          "companyDescription": "EcoTech provides environmental engineering solutions to promote sustainability.",
          "icon": "architecture.png",
          "term": "3 year+",
          "position": "Engineer",
          "experience": "4 - 6 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Biomedical Engineer",
          "company": "MediTech",
          "location": "Philadelphia, PA",
          "posted": "3 days ago",
          "salary": "$80,000 - $100,000",
          "image": "assets/logos/logo_3.10.png",
          "description": "Design and develop medical devices. Conduct research and testing.",
          "companyDescription": "MediTech specializes in biomedical engineering and medical technology solutions.",
          "icon": "architecture.png",
          "term": "4 year+",
          "position": "Engineer",
          "experience": "5 - 7 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Accountant",
          "company": "FinancePro",
          "location": "New York, NY",
          "posted": "2 days ago",
          "salary": "$60,000 - $75,000",
          "image": "assets/logos/logo_4.1.png",
          "description": "Prepare and analyze financial statements. Ensure compliance with accounting standards.",
          "companyDescription": "FinancePro provides comprehensive accounting and financial services.",
          "icon": "accounting.png",
          "term": "3 year+",
          "position": "Accountant",
          "experience": "3 - 5 years",
          "category": "Accounting"
      },
      {
          "title": "Tax Specialist",
          "company": "TaxExperts",
          "location": "San Francisco, CA",
          "posted": "3 days ago",
          "salary": "$65,000 - $80,000",
          "image": "assets/logos/logo_4.2.png",
          "description": "Prepare and file tax returns. Provide tax planning and advisory services.",
          "companyDescription": "TaxExperts offers specialized tax services for individuals and businesses.",
          "icon": "accounting.png",
          "term": "3 year+",
          "position": "Specialist",
          "experience": "4 - 6 years",
          "category": "Accounting"
      },

































];





