const jobs = [
    {
        title: "Information Technology",
        company: "ABC1 Tech",
        location: "New York, NY",
        posted: "2 days ago",
        salary: "$80,000 - $100,000",
        image: "assets/logos/logo_1.1.png",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
        companyDescription: "ABC Tech is a leading tech company specializing in software development and IT consulting. We offer a dynamic and inclusive work environment.",
        icon: "it.png",
        term: "3 year+",
        position: "manager",
        experience: "4 - 6 year",
        category: "Information Technology",
    },
    {
        "title": "Software Engineer",
        "company": "ABC Tech",
        "location": "New York, NY",
        "posted": "2 days ago",
        "salary": "$80,000 - $100,000",
        "image": "assets/logos/a.png",
        "description": "Develop and maintain software applications. Collaborate with cross-functional teams.",
        "companyDescription": "ABC Tech is a leading tech company specializing in software development and IT consulting. We offer a dynamic and inclusive work environment.",
        "icon": "it.png",
        "term": "3 year+",
        "position": "Manager",
        "experience": "4 - 6 years",
        "category": "Information Technology"
    },
    {
        "title": "Network Administrator",
        "company": "Net Solutions",
        "location": "San Jose, CA",
        "posted": "1 week ago",
        "salary": "$70,000 - $85,000",
        "image": "assets/logos/logo_1.1.png",
        "description": "Manage and maintain network infrastructure. Ensure network security and performance.",
        "companyDescription": "Net Solutions is a leading provider of network services and solutions.",
        "icon": "it.png",
        "term": "3 year+",
        "position": "Administrator",
        "experience": "3 - 5 years",
        "category": "Information Technology"
    },
    {
        "title": "Systems Analyst",
        "company": "Data Corp",
        "location": "Dallas, TX",
        "posted": "5 days ago",
        "salary": "$75,000 - $95,000",
        "image": "assets/logos/logo_1.1.png",
        "description": "Analyze and improve IT systems and processes. Work with stakeholders to gather requirements.",
        "companyDescription": "Data Corp specializes in providing data-driven solutions for various industries.",
        "icon": "it.png",
        "term": "3 year+",
        "position": "Analyst",
        "experience": "4 - 6 years",
        "category": "Information Technology"
    },
    {
        "title": "IT Support Specialist",
        "company": "Tech Help",
        "location": "Miami, FL",
        "posted": "3 days ago",
        "salary": "$50,000 - $65,000",
        "image": "assets/logos/t.png",
        "description": "Provide technical support to end-users. Troubleshoot hardware and software issues.",
        "companyDescription": "Tech Help offers comprehensive IT support services to businesses and individuals.",
        "icon": "it.png",
        "term": "2 year+",
        "position": "Specialist",
        "experience": "2 - 4 years",
        "category": "Information Technology"
    },
    {
        "title": "Database Administrator",
        "company": "Data Solutions",
        "location": "Chicago, IL",
        "posted": "1 week ago",
        "salary": "$85,000 - $105,000",
        "image": "assets/logos/logo_1.1.png",
        "description": "Manage and maintain databases. Ensure data integrity and security.",
        "companyDescription": "Data Solutions is a leader in providing data management services to enterprises.",
        "icon": "it.png",
        "term": "4 year+",
        "position": "Administrator",
        "experience": "5 - 7 years",
        "category": "Information Technology"
    },
    {
        "title": "Cloud Engineer",
        "company": "CloudTech",
        "location": "Seattle, WA",
        "posted": "4 days ago",
        "salary": "$90,000 - $110,000",
        "image": "assets/logos/c.png",
        "description": "Design and implement cloud solutions. Manage cloud infrastructure.",
        "companyDescription": "CloudTech specializes in cloud computing solutions and services.",
        "icon": "it.png",
        "term": "3 year+",
        "position": "Engineer",
        "experience": "4 - 6 years",
        "category": "Information Technology"
    },{
          "title": "DevOps Engineer",
          "company": "DevWorks",
          "location": "Austin, TX",
          "posted": "2 days ago",
          "salary": "$85,000 - $105,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Automate and streamline software development and deployment processes.",
          "companyDescription": "DevWorks provides innovative DevOps solutions to enhance software development efficiency.",
          "icon": "it.png",
          "term": "3 year+",
          "position": "Engineer",
          "experience": "4 - 6 years",
          "category": "Information Technology"
      },
      {
          "title": "Cybersecurity Analyst",
          "company": "SecureIT",
          "location": "Boston, MA",
          "posted": "1 week ago",
          "salary": "$80,000 - $100,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Identify and mitigate cybersecurity threats. Implement security measures.",
          "companyDescription": "SecureIT specializes in providing advanced cybersecurity solutions to protect businesses.",
          "icon": "it.png",
          "term": "4 year+",
          "position": "Analyst",
          "experience": "4 - 6 years",
          "category": "Information Technology"
      },
      {
          "title": "IT Project Manager",
          "company": "Project Solutions",
          "location": "Denver, CO",
          "posted": "3 days ago",
          "salary": "$90,000 - $110,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Manage and oversee IT projects. Ensure timely and successful project completion.",
          "companyDescription": "Project Solutions specializes in IT project management and consulting services.",
          "icon": "it.png",
          "term": "5 year+",
          "position": "Manager",
          "experience": "5 - 7 years",
          "category": "Information Technology"
      },
      {
          "title": "Business Analyst",
          "company": "BizTech",
          "location": "Atlanta, GA",
          "posted": "4 days ago",
          "salary": "$75,000 - $95,000",
          "image": "assets/logos/b.png",
          "description": "Analyze business processes and requirements. Provide recommendations for improvements.",
          "companyDescription": "BizTech offers business consulting and technology solutions to enhance operational efficiency.",
          "icon": "it.png",
          "term": "3 year+",
          "position": "Analyst",
          "experience": "4 - 6 years",
          "category": "Information Technology"
      },
      {
          "title": "Office Administrator",
          "company": "XYZ Corp",
          "location": "San Francisco, CA",
          "posted": "5 days ago",
          "salary": "$50,000 - $60,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Manage office operations and support staff. Ensure efficient office procedures.",
          "companyDescription": "XYZ Corp is a multinational company providing innovative solutions in various industries.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Coordinator",
          "experience": "3 - 5 years",
          "category": "Administrator"
      },
      {
          "title": "Administrative Assistant",
          "company": "Office Pro",
          "location": "New York, NY",
          "posted": "3 days ago",
          "salary": "$40,000 - $50,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Provide administrative support to the team. Manage schedules and correspondence.",
          "companyDescription": "Office Pro offers administrative support services to various businesses.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Assistant",
          "experience": "2 - 3 years",
          "category": "Administrator"
      },
      {
          "title": "Executive Assistant",
          "company": "Global Enterprises",
          "location": "Chicago, IL",
          "posted": "1 week ago",
          "salary": "$55,000 - $70,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Support senior executives. Manage calendars, travel arrangements, and communication.",
          "companyDescription": "Global Enterprises is a leading multinational company with diverse business interests.",
          "icon": "admin.png",
          "term": "3 year+",
          "position": "Assistant",
          "experience": "4 - 6 years",
          "category": "Administrator"
      },
      {
          "title": "Receptionist",
          "company": "Front Desk Inc.",
          "location": "Los Angeles, CA",
          "posted": "2 days ago",
          "salary": "$30,000 - $40,000",
          "image": "assets/logos/f.png",
          "description": "Greet visitors and manage front desk operations. Handle phone calls and inquiries.",
          "companyDescription": "Front Desk Inc. provides front office solutions and services to businesses.",
          "icon": "admin.png",
          "term": "1 year+",
          "position": "Receptionist",
          "experience": "1 - 2 years",
          "category": "Administrator"
      },
      {
          "title": "HR Administrator",
          "company": "PeopleFirst",
          "location": "Houston, TX",
          "posted": "4 days ago",
          "salary": "$45,000 - $60,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Manage HR operations and employee records. Support recruitment and onboarding processes.",
          "companyDescription": "PeopleFirst specializes in human resources and talent management services.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Administrator",
          "experience": "3 - 5 years",
          "category": "Administrator"
      },
      {
          "title": "Office Manager",
          "company": "BizOffice",
          "location": "Seattle, WA",
          "posted": "3 days ago",
          "salary": "$60,000 - $75,000",
          "image": "assets/logos/b.png",
          "description": "Oversee office operations and staff. Ensure efficient workflow and productivity.",
          "companyDescription": "BizOffice provides office management solutions to enhance business efficiency.",
          "icon": "admin.png",
          "term": "3 year+",
          "position": "Manager",
          "experience": "4 - 6 years",
          "category": "Administrator"
      },
      {
          "title": "Data Entry Clerk",
          "company": "DataWorks",
          "location": "Boston, MA",
          "posted": "1 week ago",
          "salary": "$35,000 - $45,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Enter and update data in systems. Ensure accuracy and data integrity.",
          "companyDescription": "DataWorks offers data entry and management services to businesses.",
          "icon": "admin.png",
          "term": "1 year+",
          "position": "Clerk",
          "experience": "1 - 2 years",
          "category": "Administrator"
      },
      {
          "title": "Logistics Coordinator",
          "company": "LogiTech",
          "location": "Miami, FL",
          "posted": "5 days ago",
          "salary": "$50,000 - $65,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Coordinate logistics and supply chain operations. Manage shipments and inventory.",
          "companyDescription": "LogiTech specializes in logistics and supply chain management solutions.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Coordinator",
          "experience": "3 - 5 years",
          "category": "Administrator"
      },
      {
          "title": "Customer Service Administrator",
          "company": "ClientFirst",
          "location": "Atlanta, GA",
          "posted": "4 days ago",
          "salary": "$45,000 - $55,000",
          "image": "assets/logos/c.png",
          "description": "Manage customer service operations. Handle customer inquiries and support requests.",
          "companyDescription": "ClientFirst provides customer service and support solutions to businesses.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Administrator",
          "experience": "2 - 4 years",
          "category": "Administrator"
      },
      {
          "title": "Project Administrator",
          "company": "ProjManage",
          "location": "Denver, CO",
          "posted": "3 days ago",
          "salary": "$55,000 - $70,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Support project managers in planning and executing projects. Maintain project documentation.",
          "companyDescription": "ProjManage offers project management and administrative support services.",
          "icon": "admin.png",
          "term": "2 year+",
          "position": "Administrator",
          "experience": "3 - 5 years",
          "category": "Administrator"
      },
      {
          "title": "Architect",
          "company": "Design Innovations",
          "location": "Chicago, IL",
          "posted": "3 days ago",
          "salary": "$70,000 - $90,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Design and oversee construction projects. Work with clients to meet their needs.",
          "companyDescription": "Design Innovations is a top architecture firm known for innovative and sustainable designs.",
          "icon": "architecture.png",
          "term": "5 year+",
          "position": "Senior Architect",
          "experience": "7 - 10 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Civil Engineer",
          "company": "BuildRight",
          "location": "New York, NY",
          "posted": "4 days ago",
          "salary": "$80,000 - $100,000",
          "image": "assets/logos/b.png",
          "description": "Plan and oversee construction projects. Ensure compliance with regulations.",
          "companyDescription": "BuildRight specializes in civil engineering and construction management services.",
          "icon": "architecture.png",
          "term": "5 year+",
          "position": "Engineer",
          "experience": "5 - 7 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Mechanical Engineer",
          "company": "TechMech",
          "location": "Los Angeles, CA",
          "posted": "5 days ago",
          "salary": "$75,000 - $95,000",
          "image": "assets/logos/t.png",
          "description": "Design and develop mechanical systems. Conduct performance testing and analysis.",
          "companyDescription": "TechMech offers innovative mechanical engineering solutions for various industries.",
          "icon": "architecture.png",
          "term": "3 year+",
          "position": "Engineer",
          "experience": "4 - 6 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Electrical Engineer",
          "company": "ElectroTech",
          "location": "San Francisco, CA",
          "posted": "1 week ago",
          "salary": "$80,000 - $100,000",
          "image": "assets/logos/e.png",
          "description": "Design and implement electrical systems. Ensure safety and efficiency.",
          "companyDescription": "ElectroTech specializes in electrical engineering and power systems.",
          "icon": "architecture.png",
          "term": "4 year+",
          "position": "Engineer",
          "experience": "5 - 7 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Structural Engineer",
          "company": "Structura",
          "location": "Seattle, WA",
          "posted": "3 days ago",
          "salary": "$85,000 - $105,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Design and analyze structural components. Ensure structural integrity and safety.",
          "companyDescription": "Structura offers structural engineering services for residential and commercial projects.",
          "icon": "architecture.png",
          "term": "4 year+",
          "position": "Engineer",
          "experience": "5 - 7 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Urban Planner",
          "company": "CityPlan",
          "location": "Boston, MA",
          "posted": "2 days ago",
          "salary": "$70,000 - $90,000",
          "image": "assets/logos/c.png",
          "description": "Develop and implement urban planning projects. Work with city officials and stakeholders.",
          "companyDescription": "CityPlan specializes in urban planning and sustainable development projects.",
          "icon": "architecture.png",
          "term": "3 year+",
          "position": "Planner",
          "experience": "4 - 6 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Landscape Architect",
          "company": "GreenScapes",
          "location": "Denver, CO",
          "posted": "1 week ago",
          "salary": "$65,000 - $85,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Design and plan outdoor spaces. Ensure sustainable and aesthetic landscape solutions.",
          "companyDescription": "GreenScapes offers landscape architecture services for residential and commercial properties.",
          "icon": "architecture.png",
          "term": "3 year+",
          "position": "Architect",
          "experience": "4 - 6 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Industrial Engineer",
          "company": "IndusTech",
          "location": "Houston, TX",
          "posted": "4 days ago",
          "salary": "$75,000 - $95,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Optimize manufacturing processes. Improve efficiency and reduce costs.",
          "companyDescription": "IndusTech specializes in industrial engineering and process optimization services.",
          "icon": "architecture.png",
          "term": "4 year+",
          "position": "Engineer",
          "experience": "5 - 7 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Environmental Engineer",
          "company": "EcoTech",
          "location": "Miami, FL",
          "posted": "5 days ago",
          "salary": "$70,000 - $90,000",
          "image": "assets/logos/e.png",
          "description": "Develop and implement environmental protection plans. Conduct impact assessments.",
          "companyDescription": "EcoTech provides environmental engineering solutions to promote sustainability.",
          "icon": "architecture.png",
          "term": "3 year+",
          "position": "Engineer",
          "experience": "4 - 6 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Biomedical Engineer",
          "company": "MediTech",
          "location": "Philadelphia, PA",
          "posted": "3 days ago",
          "salary": "$80,000 - $100,000",
          "image": "assets/logos/logo_1.1.png",
          "description": "Design and develop medical devices. Conduct research and testing.",
          "companyDescription": "MediTech specializes in biomedical engineering and medical technology solutions.",
          "icon": "architecture.png",
          "term": "4 year+",
          "position": "Engineer",
          "experience": "5 - 7 years",
          "category": "Architecture/Engineering"
      },
      {
          "title": "Accountant",
          "company": "FinancePro",
          "location": "New York, NY",
          "posted": "2 days ago",
          "salary": "$60,000 - $75,000",
          "image": "assets/logos/f.png",
          "description": "Prepare and analyze financial statements. Ensure compliance with accounting standards.",
          "companyDescription": "FinancePro provides comprehensive accounting and financial services.",
          "icon": "accounting.png",
          "term": "3 year+",
          "position": "Accountant",
          "experience": "3 - 5 years",
          "category": "Accounting"
      },
      {
          "title": "Tax Specialist",
          "company": "TaxExperts",
          "location": "San Francisco, CA",
          "posted": "3 days ago",
          "salary": "$65,000 - $80,000",
          "image": "assets/logos/t.png",
          "description": "Prepare and file tax returns. Provide tax planning and advisory services.",
          "companyDescription": "TaxExperts offers specialized tax services for individuals and businesses.",
          "icon": "accounting.png",
          "term": "3 year+",
          "position": "Specialist",
          "experience": "4 - 6 years",
          "category": "Accounting"
      },
      {
        "title": "Junior Accountant",
        "company": "Financial Consultants Inc.",
        "location": "New York, NY",
        "posted": "2 days ago",
        "salary": "$45,000 - $55,000",
        "image": "assets/logos/f.png",
        "description": "Assist with financial reporting, bookkeeping, and payroll processing. Prepare monthly financial statements and reconcile accounts.",
        "companyDescription": "Financial Consultants Inc. provides accounting and financial consulting services to a diverse client base.",
        "icon": "accounting.png",
        "term": "Permanent",
        "position": "Junior Accountant",
        "experience": "0 - 2 years",
        "category": "Accounting"
    },
    {
        "title": "Senior Auditor",
        "company": "Audit Solutions Group",
        "location": "Los Angeles, CA",
        "posted": "1 week ago",
        "salary": "$70,000 - $85,000",
        "image": "assets/logos/a.png",
        "description": "Conduct audits, review financial records, and assess internal controls. Prepare audit reports and provide recommendations.",
        "companyDescription": "Audit Solutions Group offers audit, tax, and advisory services to clients across various industries.",
        "icon": "accounting.png",
        "term": "Permanent",
        "position": "Senior Auditor",
        "experience": "3 - 5 years",
        "category": "Accounting"
    },
    {
        "title": "Tax Analyst",
        "company": "Tax Specialists Inc.",
        "location": "Chicago, IL",
        "posted": "5 days ago",
        "salary": "$60,000 - $75,000",
        "image": "assets/logos/t.png",
        "description": "Prepare tax returns, analyze tax regulations, and provide tax planning advice. Assist with tax audits and compliance.",
        "companyDescription": "Tax Specialists Inc. specializes in tax consulting and advisory services for individuals and businesses.",
        "icon": "accounting.png",
        "term": "Permanent",
        "position": "Tax Analyst",
        "experience": "2 - 4 years",
        "category": "Accounting"
    },
    {
        "title": "Financial Controller",
        "company": "Global Finance Solutions",
        "location": "Houston, TX",
        "posted": "3 days ago",
        "salary": "$90,000 - $110,000",
        "image": "assets/logos/logo_accounting_4.png",
        "description": "Manage financial reporting, budgeting, and forecasting activities. Oversee accounting operations and ensure compliance.",
        "companyDescription": "Global Finance Solutions provides comprehensive financial services including accounting, investments, and consulting.",
        "icon": "accounting.png",
        "term": "Permanent",
        "position": "Financial Controller",
        "experience": "5 - 7 years",
        "category": "Accounting"
    },
    {
        "title": "Accounts Payable Specialist",
        "company": "Accounts Payable Experts",
        "location": "Miami, FL",
        "posted": "1 week ago",
        "salary": "$50,000 - $60,000",
        "image": "assets/logos/a.png",
        "description": "Process accounts payable transactions, reconcile vendor statements, and resolve invoice discrepancies.",
        "companyDescription": "Accounts Payable Experts provides specialized accounts payable outsourcing and consulting services.",
        "icon": "accounting.png",
        "term": "Permanent",
        "position": "Accounts Payable Specialist",
        "experience": "2 - 4 years",
        "category": "Accounting"
    },
    {
        "title": "Financial Analyst",
        "company": "Finance Dynamics",
        "location": "Seattle, WA",
        "posted": "4 days ago",
        "salary": "$65,000 - $80,000",
        "image": "assets/logos/f.png",
        "description": "Analyze financial data, prepare forecasts, and create financial models. Provide insights to support decision-making.",
        "companyDescription": "Finance Dynamics offers financial consulting services to help businesses optimize their financial performance.",
        "icon": "accounting.png",
        "term": "Permanent",
        "position": "Financial Analyst",
        "experience": "2 - 4 years",
        "category": "Accounting"
    },
    {
        "title": "Full Stack Developer",
        "company": "Tech Innovators",
        "location": "San Francisco, CA",
        "posted": "1 day ago",
        "salary": "$90,000 - $120,000",
        "image": "assets/logos/t.png",
        "description": "Design and develop scalable web applications. Work with front-end and back-end technologies.",
        "companyDescription": "Tech Innovators is a cutting-edge software development firm known for innovative solutions and dynamic projects.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Developer",
        "experience": "3 - 5 years",
        "category": "Software Engineering"
    },
    {
        "title": "Frontend Developer",
        "company": "Creative Solutions",
        "location": "Austin, TX",
        "posted": "3 days ago",
        "salary": "$75,000 - $95,000",
        "image": "assets/logos/c.png",
        "description": "Implement user interfaces and improve user experience. Collaborate with UI/UX designers.",
        "companyDescription": "Creative Solutions specializes in user-centric software design and development.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Developer",
        "experience": "2 - 4 years",
        "category": "Software Engineering"
    },
    {
        "title": "Backend Developer",
        "company": "SecureTech",
        "location": "Seattle, WA",
        "posted": "1 week ago",
        "salary": "$80,000 - $110,000",
        "image": "assets/logos/logo_2.3.png",
        "description": "Develop server-side logic and database structures. Ensure high performance and responsiveness.",
        "companyDescription": "SecureTech is a leading provider of security-focused software solutions.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Developer",
        "experience": "3 - 5 years",
        "category": "Software Engineering"
    },
    {
        "title": "DevOps Engineer",
        "company": "CloudWorks",
        "location": "Denver, CO",
        "posted": "2 days ago",
        "salary": "$85,000 - $105,000",
        "image": "assets/logos/c.png",
        "description": "Automate and streamline operations and processes. Build and maintain tools for deployment and monitoring.",
        "companyDescription": "CloudWorks provides state-of-the-art cloud solutions and services to various industries.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Engineer",
        "experience": "3 - 5 years",
        "category": "Software Engineering"
    },
    {
        "title": "Software Architect",
        "company": "NextGen Solutions",
        "location": "Boston, MA",
        "posted": "2 days ago",
        "salary": "$120,000 - $150,000",
        "image": "assets/logos/logo_3.1.png",
        "description": "Design and oversee the architecture of software systems. Ensure scalability and performance.",
        "companyDescription": "NextGen Solutions is at the forefront of providing next-generation software and technology solutions.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Architect",
        "experience": "7 - 10 years",
        "category": "Software Engineering"
    },
    {
        "title": "Mobile App Developer",
        "company": "App Masters",
        "location": "Los Angeles, CA",
        "posted": "4 days ago",
        "salary": "$85,000 - $105,000",
        "image": "assets/logos/a.png",
        "description": "Develop and maintain mobile applications for iOS and Android platforms.",
        "companyDescription": "App Masters specializes in creating innovative and user-friendly mobile applications.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Developer",
        "experience": "2 - 4 years",
        "category": "Software Engineering"
    },
    {
        "title": "Data Scientist",
        "company": "Data Insights",
        "location": "Chicago, IL",
        "posted": "3 days ago",
        "salary": "$95,000 - $125,000",
        "image": "assets/logos/logo_3.3.png",
        "description": "Analyze and interpret complex data sets to provide insights and recommendations.",
        "companyDescription": "Data Insights provides data-driven solutions to help businesses make informed decisions.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Scientist",
        "experience": "3 - 5 years",
        "category": "Software Engineering"
    },
    {
        "title": "Machine Learning Engineer",
        "company": "AI Innovations",
        "location": "Palo Alto, CA",
        "posted": "5 days ago",
        "salary": "$110,000 - $140,000",
        "image": "assets/logos/a.png",
        "description": "Build and deploy machine learning models. Collaborate with data scientists and software engineers.",
        "companyDescription": "AI Innovations is a leader in artificial intelligence and machine learning technologies.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Engineer",
        "experience": "3 - 5 years",
        "category": "Software Engineering"
    },
    {
        "title": "QA Engineer",
        "company": "Quality Matters",
        "location": "Houston, TX",
        "posted": "1 week ago",
        "salary": "$70,000 - $90,000",
        "image": "assets/logos/logo_3.5.png",
        "description": "Conduct software testing to ensure quality and functionality. Develop automated test scripts.",
        "companyDescription": "Quality Matters focuses on delivering high-quality software products through rigorous testing.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Engineer",
        "experience": "2 - 4 years",
        "category": "Software Engineering"
    },
    {
        "title": "Product Manager",
        "company": "Tech Visionaries",
        "location": "New York, NY",
        "posted": "2 days ago",
        "salary": "$100,000 - $130,000",
        "image": "assets/logos/t.png",
        "description": "Lead product development from concept to launch. Define product roadmap and strategy.",
        "companyDescription": "Tech Visionaries is known for pioneering products in the tech industry.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Manager",
        "experience": "5 - 7 years",
        "category": "Software Engineering"
    },
    {
        "title": "UI/UX Designer",
        "company": "Design Pros",
        "location": "Portland, OR",
        "posted": "4 days ago",
        "salary": "$75,000 - $95,000",
        "image": "assets/logos/logo_3.7.png",
        "description": "Design intuitive and engaging user interfaces. Conduct user research and usability testing.",
        "companyDescription": "Design Pros specializes in creating visually appealing and user-friendly software interfaces.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Designer",
        "experience": "2 - 4 years",
        "category": "Software Engineering"
    },
    {
        "title": "Cloud Engineer",
        "company": "Cloud Solutions",
        "location": "Atlanta, GA",
        "posted": "5 days ago",
        "salary": "$90,000 - $120,000",
        "image": "assets/logos/c.png",
        "description": "Design and implement cloud-based solutions. Ensure security and scalability of cloud infrastructure.",
        "companyDescription": "Cloud Solutions provides comprehensive cloud computing services and solutions.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Engineer",
        "experience": "3 - 5 years",
        "category": "Software Engineering"
    },
    {
        "title": "Security Engineer",
        "company": "SecureWorks",
        "location": "Washington, DC",
        "posted": "3 days ago",
        "salary": "$95,000 - $125,000",
        "image": "assets/logos/logo_3.9.png",
        "description": "Implement security measures to protect software and data. Conduct security assessments and audits.",
        "companyDescription": "SecureWorks specializes in cybersecurity and protecting sensitive information.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Engineer",
        "experience": "3 - 5 years",
        "category": "Software Engineering"
    },
    {
        "title": "Embedded Systems Engineer",
        "company": "Embedded Tech",
        "location": "Raleigh, NC",
        "posted": "4 days ago",
        "salary": "$85,000 - $110,000",
        "image": "assets/logos/e.png",
        "description": "Develop and maintain embedded software for various devices. Work with hardware and firmware.",
        "companyDescription": "Embedded Tech focuses on creating embedded systems for various industries.",
        "icon": "software_engineering.png",
        "term": "Permanent",
        "position": "Engineer",
        "experience": "3 - 5 years",
        "category": "Software Engineering"
    },
    {
        "title": "Senior Graphic Designer",
        "company": "Creative Minds",
        "location": "San Francisco, CA",
        "posted": "2 days ago",
        "salary": "$75,000 - $90,000",
        "image": "assets/logos/c.png",
        "description": "Lead design projects from concept to completion. Collaborate with marketing and product teams.",
        "companyDescription": "Creative Minds is a leading design agency known for innovative and impactful designs.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Senior Designer",
        "experience": "5 - 7 years",
        "category": "Graphic Design"
    },
    {
        "title": "Junior Graphic Designer",
        "company": "Pixel Perfect",
        "location": "Austin, TX",
        "posted": "3 days ago",
        "salary": "$45,000 - $55,000",
        "image": "assets/logos/logo_4.2.png",
        "description": "Assist in creating visual content for various media. Support senior designers in project execution.",
        "companyDescription": "Pixel Perfect is a creative studio specializing in branding and visual communication.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Junior Designer",
        "experience": "0 - 2 years",
        "category": "Graphic Design"
    },
    {
        "title": "Web Designer",
        "company": "Web Wonders",
        "location": "Seattle, WA",
        "posted": "4 days ago",
        "salary": "$60,000 - $75,000",
        "image": "assets/logos/logo_4.3.png",
        "description": "Design and maintain website layouts. Ensure user-friendly and visually appealing interfaces.",
        "companyDescription": "Web Wonders specializes in web design and development, creating stunning online experiences.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Designer",
        "experience": "2 - 4 years",
        "category": "Graphic Design"
    },
    {
        "title": "Illustrator",
        "company": "Artistic Expressions",
        "location": "New York, NY",
        "posted": "5 days ago",
        "salary": "$50,000 - $65,000",
        "image": "assets/logos/a.png",
        "description": "Create illustrations for print and digital media. Collaborate with clients to bring their vision to life.",
        "companyDescription": "Artistic Expressions is a creative agency specializing in bespoke illustrations and art.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Illustrator",
        "experience": "2 - 4 years",
        "category": "Graphic Design"
    },
    {
        "title": "UI/UX Designer",
        "company": "User First",
        "location": "Los Angeles, CA",
        "posted": "1 week ago",
        "salary": "$80,000 - $100,000",
        "image": "assets/logos/logo_4.5.png",
        "description": "Design user interfaces and experiences for web and mobile applications.",
        "companyDescription": "User First focuses on creating user-centric designs for digital products.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Designer",
        "experience": "3 - 5 years",
        "category": "Graphic Design"
    },
    {
        "title": "Brand Designer",
        "company": "Brand Builders",
        "location": "Chicago, IL",
        "posted": "2 days ago",
        "salary": "$70,000 - $85,000",
        "image": "assets/logos/b.png",
        "description": "Develop and maintain brand identity for clients. Create logos, marketing materials, and more.",
        "companyDescription": "Brand Builders specializes in crafting unique and memorable brand identities.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Designer",
        "experience": "4 - 6 years",
        "category": "Graphic Design"
    },
    {
        "title": "Graphic Design Intern",
        "company": "Innovative Designs",
        "location": "Miami, FL",
        "posted": "3 days ago",
        "salary": "$30,000 - $35,000",
        "image": "assets/logos/logo_4.7.png",
        "description": "Support design team in various projects. Gain hands-on experience in graphic design.",
        "companyDescription": "Innovative Designs offers creative solutions and aims to foster new design talent.",
        "icon": "graphic_design.png",
        "term": "Internship",
        "position": "Intern",
        "experience": "0 - 1 year",
        "category": "Graphic Design"
    },
    {
        "title": "Freelance Graphic Designer",
        "company": "Freelance",
        "location": "Remote",
        "posted": "5 days ago",
        "salary": "$25 - $35/hour",
        "image": "assets/logos/f.png",
        "description": "Work on various design projects remotely. Flexible hours and project-based work.",
        "companyDescription": "Freelance platform connecting talented graphic designers with clients worldwide.",
        "icon": "graphic_design.png",
        "term": "Freelance",
        "position": "Designer",
        "experience": "2 - 5 years",
        "category": "Graphic Design"
    },
    {
        "title": "Motion Graphics Designer",
        "company": "Motion Magic",
        "location": "Denver, CO",
        "posted": "4 days ago",
        "salary": "$70,000 - $90,000",
        "image": "assets/logos/logo_4.9.png",
        "description": "Create engaging motion graphics for videos and animations.",
        "companyDescription": "Motion Magic specializes in creating dynamic and impactful motion graphics.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Designer",
        "experience": "3 - 5 years",
        "category": "Graphic Design"
    },
    {
        "title": "Packaging Designer",
        "company": "Pack Perfect",
        "location": "Portland, OR",
        "posted": "3 days ago",
        "salary": "$60,000 - $75,000",
        "image": "assets/logos/logo_4.10.png",
        "description": "Design packaging for various products, ensuring functionality and aesthetics.",
        "companyDescription": "Pack Perfect specializes in innovative and sustainable packaging solutions.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Designer",
        "experience": "2 - 4 years",
        "category": "Graphic Design"
    },
    {
        "title": "Creative Director",
        "company": "Visionary Creations",
        "location": "New York, NY",
        "posted": "2 days ago",
        "salary": "$120,000 - $150,000",
        "image": "assets/logos/v.png",
        "description": "Lead and inspire the creative team. Oversee all design projects and ensure brand consistency.",
        "companyDescription": "Visionary Creations is a top-tier creative agency delivering high-impact visual solutions.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Director",
        "experience": "7 - 10 years",
        "category": "Graphic Design"
    },
    {
        "title": "Infographic Designer",
        "company": "InfoGraphix",
        "location": "Boston, MA",
        "posted": "5 days ago",
        "salary": "$55,000 - $70,000",
        "image": "assets/logos/logo_4.12.png",
        "description": "Design compelling infographics to visually represent data and information.",
        "companyDescription": "InfoGraphix specializes in data visualization and creating informative infographics.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Designer",
        "experience": "2 - 4 years",
        "category": "Graphic Design"
    },
    {
        "title": "Art Director",
        "company": "Creative Vision",
        "location": "Los Angeles, CA",
        "posted": "4 days ago",
        "salary": "$100,000 - $130,000",
        "image": "assets/logos/c.png",
        "description": "Oversee the visual style and content of magazines, newspapers, and product packaging.",
        "companyDescription": "Creative Vision is known for setting trends and pushing the boundaries of visual design.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Director",
        "experience": "6 - 8 years",
        "category": "Graphic Design"
    },
    {
        "title": "Visual Designer",
        "company": "Visual Solutions",
        "location": "Phoenix, AZ",
        "posted": "3 days ago",
        "salary": "$65,000 - $80,000",
        "image": "assets/logos/v.png",
        "description": "Create visually appealing designs for websites, applications, and print materials.",
        "companyDescription": "Visual Solutions provides cutting-edge design services for digital and print media.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Designer",
        "experience": "3 - 5 years",
        "category": "Graphic Design"
    },
    {
        "title": "Digital Illustrator",
        "company": "Illustrate It",
        "location": "San Diego, CA",
        "posted": "1 week ago",
        "salary": "$55,000 - $70,000",
        "image": "assets/logos/logo_4.15.png",
        "description": "Create digital illustrations for marketing campaigns, websites, and social media.",
        "companyDescription": "Illustrate It is a digital agency specializing in custom illustrations for various platforms.",
        "icon": "graphic_design.png",
        "term": "Permanent",
        "position": "Illustrator",
        "experience": "2 - 4 years",
        "category": "Graphic Design"
    },
    {
        "title": "Customer Service Representative",
        "company": "HelpDesk Inc.",
        "location": "New York, NY",
        "posted": "2 days ago",
        "salary": "$35,000 - $45,000",
        "image": "assets/logos/logo_5.1.png",
        "description": "Provide support to customers via phone and email. Resolve customer inquiries and complaints.",
        "companyDescription": "HelpDesk Inc. is a leading provider of customer support services for various industries.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Representative",
        "experience": "1 - 3 years",
        "category": "Customer Service"
    },
    {
        "title": "Call Center Agent",
        "company": "Call Connect",
        "location": "San Francisco, CA",
        "posted": "3 days ago",
        "salary": "$30,000 - $40,000",
        "image": "assets/logos/c.png",
        "description": "Handle inbound and outbound calls. Provide information and support to customers.",
        "companyDescription": "Call Connect operates call centers providing exceptional customer service solutions.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Agent",
        "experience": "0 - 2 years",
        "category": "Customer Service"
    },
    {
        "title": "Technical Support Specialist",
        "company": "Tech Solutions",
        "location": "Austin, TX",
        "posted": "4 days ago",
        "salary": "$40,000 - $55,000",
        "image": "assets/logos/t.png",
        "description": "Assist customers with technical issues. Provide troubleshooting and problem-solving assistance.",
        "companyDescription": "Tech Solutions offers comprehensive tech support and IT services.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Specialist",
        "experience": "2 - 4 years",
        "category": "Customer Service"
    },
    {
        "title": "Customer Service Manager",
        "company": "Retail World",
        "location": "Chicago, IL",
        "posted": "5 days ago",
        "salary": "$60,000 - $75,000",
        "image": "assets/logos/r.png",
        "description": "Oversee the customer service team. Ensure high levels of customer satisfaction.",
        "companyDescription": "Retail World is a global retail company focused on customer-centric solutions.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Manager",
        "experience": "4 - 6 years",
        "category": "Customer Service"
    },
    {
        "title": "Customer Success Specialist",
        "company": "Success Inc.",
        "location": "Los Angeles, CA",
        "posted": "1 week ago",
        "salary": "$50,000 - $65,000",
        "image": "assets/logos/logo_5.5.png",
        "description": "Ensure customer satisfaction and success with our products. Provide ongoing support and guidance.",
        "companyDescription": "Success Inc. specializes in customer success strategies for B2B clients.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Specialist",
        "experience": "3 - 5 years",
        "category": "Customer Service"
    },
    {
        "title": "Client Services Representative",
        "company": "Biz Solutions",
        "location": "Miami, FL",
        "posted": "2 days ago",
        "salary": "$35,000 - $45,000",
        "image": "assets/logos/b.png",
        "description": "Manage client accounts and provide support. Ensure client needs are met promptly.",
        "companyDescription": "Biz Solutions offers business services and support to a wide range of clients.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Representative",
        "experience": "1 - 3 years",
        "category": "Customer Service"
    },
    {
        "title": "Customer Experience Coordinator",
        "company": "ExperienceX",
        "location": "Seattle, WA",
        "posted": "3 days ago",
        "salary": "$45,000 - $55,000",
        "image": "assets/logos/e.png",
        "description": "Coordinate customer experience initiatives. Ensure seamless customer journeys.",
        "companyDescription": "ExperienceX focuses on enhancing customer experiences across multiple channels.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Coordinator",
        "experience": "2 - 4 years",
        "category": "Customer Service"
    },
    {
        "title": "Support Agent",
        "company": "SupportPro",
        "location": "Denver, CO",
        "posted": "4 days ago",
        "salary": "$30,000 - $40,000",
        "image": "assets/logos/logo_5.8.png",
        "description": "Provide support through chat, email, and phone. Resolve customer issues efficiently.",
        "companyDescription": "SupportPro offers professional support services to various industries.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Agent",
        "experience": "0 - 2 years",
        "category": "Customer Service"
    },
    {
        "title": "Customer Service Supervisor",
        "company": "Care Solutions",
        "location": "Portland, OR",
        "posted": "5 days ago",
        "salary": "$50,000 - $65,000",
        "image": "assets/logos/c.png",
        "description": "Supervise customer service team. Ensure adherence to service standards and policies.",
        "companyDescription": "Care Solutions is dedicated to providing excellent customer care and support services.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Supervisor",
        "experience": "3 - 5 years",
        "category": "Customer Service"
    },
    {
        "title": "Client Support Specialist",
        "company": "ClientFirst",
        "location": "Boston, MA",
        "posted": "2 days ago",
        "salary": "$40,000 - $55,000",
        "image": "assets/logos/c.png",
        "description": "Provide dedicated support to clients. Address and resolve client concerns.",
        "companyDescription": "ClientFirst specializes in client support and relationship management.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Specialist",
        "experience": "2 - 4 years",
        "category": "Customer Service"
    },
    {
        "title": "Customer Support Representative",
        "company": "Service Solutions",
        "location": "Phoenix, AZ",
        "posted": "3 days ago",
        "salary": "$35,000 - $45,000",
        "image": "assets/logos/logo_5.11.png",
        "description": "Assist customers with their inquiries. Provide excellent customer support.",
        "companyDescription": "Service Solutions provides comprehensive customer support services.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Representative",
        "experience": "1 - 3 years",
        "category": "Customer Service"
    },
    {
        "title": "Customer Care Specialist",
        "company": "CarePro",
        "location": "Dallas, TX",
        "posted": "4 days ago",
        "salary": "$40,000 - $55,000",
        "image": "assets/logos/c.png",
        "description": "Provide exceptional customer care. Resolve customer issues and provide information.",
        "companyDescription": "CarePro is committed to delivering outstanding customer care services.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Specialist",
        "experience": "2 - 4 years",
        "category": "Customer Service"
    },
    {
        "title": "Bilingual Customer Service Representative",
        "company": "MultiLingual Support",
        "location": "Houston, TX",
        "posted": "5 days ago",
        "salary": "$35,000 - $45,000",
        "image": "assets/logos/logo_5.13.png",
        "description": "Provide support to customers in multiple languages. Handle inquiries and complaints.",
        "companyDescription": "MultiLingual Support provides customer service in various languages.",
        "icon": "customer_service.png",
        "term": "Permanent",
        "position": "Representative",
        "experience": "1 - 3 years",
        "category": "Customer Service"
    },
    {
        "title": "Elementary School Teacher",
        "company": "Sunshine Academy",
        "location": "Los Angeles, CA",
        "posted": "2 days ago",
        "salary": "$45,000 - $55,000",
        "image": "assets/logos/logo_6.1.png",
        "description": "Teach elementary students various subjects. Create engaging lesson plans and assess student progress.",
        "companyDescription": "Sunshine Academy is committed to providing quality education in a nurturing environment.",
        "icon": "education.png",
        "term": "Permanent",
        "position": "Teacher",
        "experience": "2 - 4 years",
        "category": "Education"
    },
    {
        "title": "High School Math Teacher",
        "company": "Summit High School",
        "location": "Chicago, IL",
        "posted": "3 days ago",
        "salary": "$50,000 - $65,000",
        "image": "assets/logos/logo_6.2.png",
        "description": "Teach high school students mathematics. Prepare students for exams and promote critical thinking.",
        "companyDescription": "Summit High School focuses on academic excellence and student success.",
        "icon": "education.png",
        "term": "Permanent",
        "position": "Teacher",
        "experience": "3 - 5 years",
        "category": "Education"
    },
    {
        "title": "College Admissions Counselor",
        "company": "Admissions Experts",
        "location": "New York, NY",
        "posted": "4 days ago",
        "salary": "$55,000 - $70,000",
        "image": "assets/logos/a.png",
        "description": "Assist students with college applications and admissions process. Provide guidance and support.",
        "companyDescription": "Admissions Experts specializes in college admissions counseling and career guidance.",
        "icon": "education.png",
        "term": "Permanent",
        "position": "Counselor",
        "experience": "3 - 5 years",
        "category": "Education"
    },
    {
        "title": "ESL Teacher",
        "company": "Global Learning Center",
        "location": "Houston, TX",
        "posted": "5 days ago",
        "salary": "$40,000 - $50,000",
        "image": "assets/logos/logo_6.4.png",
        "description": "Teach English as a Second Language (ESL) to students. Develop language skills and cultural understanding.",
        "companyDescription": "Global Learning Center offers language learning programs for international students.",
        "icon": "education.png",
        "term": "Permanent",
        "position": "Teacher",
        "experience": "2 - 4 years",
        "category": "Education"
    },
    {
        "title": "Special Education Teacher",
        "company": "Inclusive Schools",
        "location": "Philadelphia, PA",
        "posted": "6 days ago",
        "salary": "$45,000 - $60,000",
        "image": "assets/logos/logo_6.5.png",
        "description": "Provide specialized instruction to students with disabilities. Develop individualized education plans (IEPs).",
        "companyDescription": "Inclusive Schools promotes inclusive education and supports students with diverse needs.",
        "icon": "education.png",
        "term": "Permanent",
        "position": "Teacher",
        "experience": "3 - 5 years",
        "category": "Education"
    },
    {
        "title": "Online Tutor",
        "company": "Virtual Learning Solutions",
        "location": "Remote",
        "posted": "1 week ago",
        "salary": "$25 - $40 per hour",
        "image": "assets/logos/logo_6.6.png",
        "description": "Provide virtual tutoring sessions to students. Help students with homework and academic subjects.",
        "companyDescription": "Virtual Learning Solutions offers online tutoring services to students globally.",
        "icon": "education.png",
        "term": "Contract",
        "position": "Tutor",
        "experience": "1 - 3 years",
        "category": "Education"
    },
    {
        "title": "Financial Analyst",
        "company": "Finance First",
        "location": "New York, NY",
        "posted": "2 days ago",
        "salary": "$70,000 - $90,000",
        "image": "assets/logos/f.png",
        "description": "Conduct financial analysis, prepare reports, and provide recommendations for financial decisions.",
        "companyDescription": "Finance First is a leading financial services firm specializing in investment management and advisory services.",
        "icon": "bank.png",
        "term": "Permanent",
        "position": "Analyst",
        "experience": "3 - 5 years",
        "category": "Banking"
    },
    {
        "title": "Personal Banker",
        "company": "Metro Bank",
        "location": "Chicago, IL",
        "posted": "3 days ago",
        "salary": "$50,000 - $65,000",
        "image": "assets/logos/logo_7.2.png",
        "description": "Provide personalized banking services to customers. Assist with account management and financial advice.",
        "companyDescription": "Metro Bank is a community-focused bank committed to customer satisfaction and financial empowerment.",
        "icon": "bank.png",
        "term": "Permanent",
        "position": "Banker",
        "experience": "2 - 4 years",
        "category": "Banking"
    },
    {
        "title": "Investment Advisor",
        "company": "Capital Investments",
        "location": "San Francisco, CA",
        "posted": "4 days ago",
        "salary": "$80,000 - $100,000",
        "image": "assets/logos/c.png",
        "description": "Provide investment advice and portfolio management services to clients. Develop personalized financial plans.",
        "companyDescription": "Capital Investments is a leading investment advisory firm offering wealth management services.",
        "icon": "bank.png",
        "term": "Permanent",
        "position": "Advisor",
        "experience": "4 - 6 years",
        "category": "Banking"
    },
    {
        "title": "Credit Analyst",
        "company": "Credit Solutions Inc.",
        "location": "Dallas, TX",
        "posted": "5 days ago",
        "salary": "$60,000 - $75,000",
        "image": "assets/logos/c.png",
        "description": "Analyze credit data and financial statements. Evaluate credit risk and make recommendations for loan approvals.",
        "companyDescription": "Credit Solutions Inc. provides credit analysis and risk management services to financial institutions.",
        "icon": "bank.png",
        "term": "Permanent",
        "position": "Analyst",
        "experience": "2 - 4 years",
        "category": "Banking"
    },
    {
        "title": "Branch Manager",
        "company": "Regional Bank",
        "location": "Miami, FL",
        "posted": "6 days ago",
        "salary": "$75,000 - $90,000",
        "image": "assets/logos/r.png",
        "description": "Oversee branch operations, manage staff, and ensure customer satisfaction. Drive business growth and achieve targets.",
        "companyDescription": "Regional Bank is dedicated to providing comprehensive banking services and fostering community relationships.",
        "icon": "bank.png",
        "term": "Permanent",
        "position": "Manager",
        "experience": "3 - 5 years",
        "category": "Banking"
    },
    {
        "title": "Mortgage Loan Officer",
        "company": "Home Finance Experts",
        "location": "Denver, CO",
        "posted": "1 week ago",
        "salary": "$60,000 - $80,000",
        "image": "assets/logos/logo_7.6.png",
        "description": "Assist clients with mortgage loan applications and guide them through the loan approval process. Evaluate creditworthiness.",
        "companyDescription": "Home Finance Experts specializes in mortgage lending and provides personalized financial solutions.",
        "icon": "bank.png",
        "term": "Permanent",
        "position": "Loan Officer",
        "experience": "2 - 4 years",
        "category": "Banking"
    },
    {
        "title": "Financial Advisor",
        "company": "Wealth Management Group",
        "location": "Seattle, WA",
        "posted": "1 week ago",
        "salary": "$70,000 - $85,000",
        "image": "assets/logos/logo_7.7.png",
        "description": "Provide comprehensive financial planning and investment advice to clients. Manage investment portfolios.",
        "companyDescription": "Wealth Management Group offers personalized financial services and investment strategies.",
        "icon": "bank.png",
        "term": "Permanent",
        "position": "Advisor",
        "experience": "3 - 5 years",
        "category": "Banking"
    },
    {
        "title": "Customer Service Representative",
        "company": "Banking Solutions",
        "location": "Atlanta, GA",
        "posted": "1 week ago",
        "salary": "$40,000 - $50,000",
        "image": "assets/logos/b.png",
        "description": "Assist customers with banking transactions, account inquiries, and resolve issues promptly. Provide excellent customer service.",
        "companyDescription": "Banking Solutions is committed to delivering exceptional banking services and building customer relationships.",
        "icon": "bank.png",
        "term": "Permanent",
        "position": "Representative",
        "experience": "1 - 3 years",
        "category": "Banking"
    },
    {
        "title": "Risk Manager",
        "company": "Global Finance Group",
        "location": "Houston, TX",
        "posted": "2 weeks ago",
        "salary": "$90,000 - $110,000",
        "image": "assets/logos/logo_7.9.png",
        "description": "Develop and implement risk management strategies. Evaluate potential risks and recommend mitigation measures.",
        "companyDescription": "Global Finance Group specializes in risk management and financial services.",
        "icon": "bank.png",
        "term": "Permanent",
        "position": "Manager",
        "experience": "4 - 6 years",
        "category": "Banking"
    },
    {
        "title": "Operations Specialist",
        "company": "Financial Operations Inc.",
        "location": "Boston, MA",
        "posted": "2 weeks ago",
        "salary": "$55,000 - $70,000",
        "image": "assets/logos/f.png",
        "description": "Support banking operations, monitor transactions, and ensure compliance with regulations. Resolve operational issues.",
        "companyDescription": "Financial Operations Inc. provides operational support and services to financial institutions.",
        "icon": "bank.png",
        "term": "Permanent",
        "position": "Specialist",
        "experience": "2 - 4 years",
        "category": "Banking"
    },
    {
        "title": "Front End Cashier",
        "company": "SuperMart",
        "location": "New York, NY",
        "posted": "2 days ago",
        "salary": "$30,000 - $35,000",
        "image": "assets/logos/logo_cashier_1.png",
        "description": "Operate cash register, process transactions, and provide excellent customer service. Maintain cleanliness of checkout area.",
        "companyDescription": "SuperMart is a well-established retail chain offering a wide range of grocery and household products.",
        "icon": "cashier.png",
        "term": "Permanent",
        "position": "Cashier",
        "experience": "0 - 1 year",
        "category": "Cashier"
    },
    {
        "title": "Retail Cashier",
        "company": "City Market",
        "location": "Los Angeles, CA",
        "posted": "1 week ago",
        "salary": "$28,000 - $32,000",
        "image": "assets/logos/c.png",
        "description": "Scan and bag merchandise, process payments, and assist customers with inquiries. Ensure accuracy in transactions.",
        "companyDescription": "City Market is a neighborhood grocery store dedicated to providing quality products and customer service.",
        "icon": "cashier.png",
        "term": "Permanent",
        "position": "Cashier",
        "experience": "1 - 2 years",
        "category": "Cashier"
    },
    {
        "title": "Cashier Associate",
        "company": "Quick Mart",
        "location": "Chicago, IL",
        "posted": "5 days ago",
        "salary": "$25,000 - $30,000",
        "image": "assets/logos/logo_cashier_3.png",
        "description": "Handle cash and credit transactions, assist with customer requests, and maintain store cleanliness. Provide friendly service.",
        "companyDescription": "Quick Mart offers convenience and grocery items with a focus on fast and efficient service.",
        "icon": "cashier.png",
        "term": "Permanent",
        "position": "Associate",
        "experience": "0 - 1 year",
        "category": "Cashier"
    },
    {
        "title": "Senior Cashier",
        "company": "Corner Store",
        "location": "Houston, TX",
        "posted": "3 days ago",
        "salary": "$32,000 - $36,000",
        "image": "assets/logos/c.png",
        "description": "Supervise cashier operations, handle large transactions, resolve customer issues, and ensure smooth store operations.",
        "companyDescription": "Corner Store is a convenience store chain known for its friendly service and diverse product offerings.",
        "icon": "cashier.png",
        "term": "Permanent",
        "position": "Senior Cashier",
        "experience": "2 - 4 years",
        "category": "Cashier"
    },
    {
        "title": "Cashier Manager",
        "company": "Express Mart",
        "location": "Miami, FL",
        "posted": "1 week ago",
        "salary": "$35,000 - $40,000",
        "image": "assets/logos/e.png",
        "description": "Manage cashier team, oversee daily operations, handle customer transactions, and maintain inventory accuracy.",
        "companyDescription": "Express Mart offers fast and convenient service with a focus on customer satisfaction and quality products.",
        "icon": "cashier.png",
        "term": "Permanent",
        "position": "Manager",
        "experience": "3 - 5 years",
        "category": "Cashier"
    },
    {
        "title": "Part-Time Cashier",
        "company": "Local Grocers",
        "location": "Seattle, WA",
        "posted": "4 days ago",
        "salary": "$12.50 - $15.00 per hour",
        "image": "assets/logos/logo_cashier_6.png",
        "description": "Process customer transactions, handle cash and card payments, assist with bagging, and maintain checkout area cleanliness.",
        "companyDescription": "Local Grocers is a community-focused grocery store offering fresh produce and local products.",
        "icon": "cashier.png",
        "term": "Part-Time",
        "position": "Cashier",
        "experience": "0 - 1 year",
        "category": "Cashier"
    },
];